### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [DjamesSuhanko/bbPrinter#1]
Hi @DjamesSuhanko 

we have detected that you changed the name of the library from `bbPrinter` to `PrinterDuino`, is that right? We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `PrinterDuino`? The older releases with the name `bbPrinter` will be ignored by the library manager.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 1086 - 2018/01/15 15:45:04 Scraping https://github.com/DjamesSuhanko/bbPrinter.git
JOB 1086 - 2018/01/15 15:45:05 Checking out tag: 0.1.0
JOB 1086 - 2018/01/15 15:45:05 Release bbPrinter:0.1.0 already loaded, skipping
JOB 1086 - 2018/01/15 15:45:05 Checking out tag: 0.1.1
JOB 1086 - 2018/01/15 15:45:05 Release PrinterDuino:0.1.1 has wrong library name, should be bbPrinter
```

**Comment by DjamesSuhanko** [comment]
Yes, it's ok for me. The new name is a bit more clear to everyone, I think.
I thank you to ask me!
